### PR TITLE
Add --diff-filter=M to git diff for version check

### LINKED ISSUE #20: Version number bump checking doesn't work for pull requests with multiple commits.
For example see #19. What happens is that `github.event.pull_request.base.sha` gives the hash of the commit that the pull request is based on, not the most recent commit. This works fine for the first commit in a PR, but (as in #19) on the second commit it tries to compare the second commit to the commit from before the PR, meaning that in this specific case it takes the base commit as https://github.com/czlee/debatekeeper-formats/commit/943ccb5ec645680f842edd98972d0fd9daed4fe7. 

Running `git show` on this commit while looking for `v1/formats/tgd2022.xml` gives this fatal error:

    path 'v1/formats/tgd2022.xml' exists on disk, but not in '943ccb5ec645680f842edd98972d0fd9daed4fe7'

Not sure how to go about fixing this as there doesn't seem to be an obvious way to tell a github action to "take the second to last commit".

### PR DESCRIPTION
**Pull request by czlee**
Hopefully fixes #20. See discussion there.

See also #22.

------------------------------

By submitting this pull request, I agree to license my contributions under the [MIT License](https://github.com/czlee/debatekeeper-formats/blob/main/LICENCE.md).

### CODE REVIEW

**Comment by czlee** [comment]
@daankoning thoughts appreciated 😊 (no rush of course!)

**Comment by czlee** [comment]
I also had a crack at checking that added files have version number 1, it's in the [`check-added-files` branch](https://github.com/czlee/debatekeeper-formats/tree/check-added-files), though I think that's not actually desirable, since there might be good reasons to start at 2 (_e.g._ it has been distributed informally already).

**Comment by daankoning** [comment]
Looks good to me!

May I perhaps suggest the solution that the script should still fail (or preferably just throw out a warning) in the case where the version number isn't 1 initially. This would still allow the informal distribution you mention (as they could still be merged even without the CI approving) while also avoiding people accidentally setting the version number to something bad (as it would give them a heads up).

**Comment by czlee** [comment]
> May I perhaps suggest the solution that the script should still fail (or preferably just throw out a warning) in the case where the version number isn't 1 initially. This would still allow the informal distribution you mention (as they could still be merged even without the CI approving) while also avoiding people accidentally setting the version number to something bad (as it would give them a heads up).

Yeah, this makes sense. Will do in a separate PR 😊

**Pull request merged**
