### PR TITLE
`validate.py` now also checks whether the version number has been bumped

### LINKED ISSUE #14: `validate.py` does not check that changed files also have a bumped version number
This was brought up a while ago in #13 but has not been addressed as of yet.

If @czlee doesn't have the time to get around to it I'd be happy to submit a PR.

### PR DESCRIPTION
**Pull request by daankoning**
The check for the version number is only executed when a format file has actually changed. Before approving please have a look at `file_has_changed` as the implementation of change detection is a bit iffy as of now.

closes #14

### CODE REVIEW

**Comment by daankoning** [comment]
Also note that this adds a new dependency on requests, a refactor to make it use urllib doesn't seem too hard should you deem this undesireable.

**Comment by czlee** [comment]
Oh, interesting! I guess an idea I had was to use git commands to determine whether files have changed, like, basically check Git history. I hadn't thought about doing it this way.

**Comment by czlee** [comment]
@daankoning I thought more about it and I think it's probably better to check against the old version using Git. That way, if the PR updates formats.json itself, it'll still check against the original version of the XML file. We also cover the case where the PR isn't against the current official repository commit.

The requests dependency is perfectly fine, but this also has the side effect of rendering it (and internet hits for the version checks) unnecessary.

I did this in #17, which builds on this PR—I thought it was probably too significant a change to load onto this PR 🙂 When you get a chance, let me know what you think, over at #17 (not here).

**Comment by czlee** [comment]
Incorporated into these merged PRs:
- #17
- #18

**Pull request closed without merging**
