### PR TITLE
Make the version number checking ignore new files

### LINKED ISSUE #20: Version number bump checking doesn't work for pull requests with multiple commits.
For example see #19. What happens is that `github.event.pull_request.base.sha` gives the hash of the commit that the pull request is based on, not the most recent commit. This works fine for the first commit in a PR, but (as in #19) on the second commit it tries to compare the second commit to the commit from before the PR, meaning that in this specific case it takes the base commit as https://github.com/czlee/debatekeeper-formats/commit/943ccb5ec645680f842edd98972d0fd9daed4fe7. 

Running `git show` on this commit while looking for `v1/formats/tgd2022.xml` gives this fatal error:

    path 'v1/formats/tgd2022.xml' exists on disk, but not in '943ccb5ec645680f842edd98972d0fd9daed4fe7'

Not sure how to go about fixing this as there doesn't seem to be an obvious way to tell a github action to "take the second to last commit".

### PR DESCRIPTION
**Pull request by daankoning**
Because `git show` exits with code 128 if the file isn't found in the commit it is sufficient to catch this and ignore it.

closes #20 

By submitting this pull request, I agree to license my contributions under the [MIT License](https://github.com/czlee/debatekeeper-formats/blob/main/LICENCE.md).

### CODE REVIEW

**Comment by daankoning** [comment]
This failure is even weirder as trying to reproduce this locally (on the same branch) gave, for both the entire script and the `git diff`, gives perfectly fine results:

Screenshot 2023-01-04 at 21 49 06

This suggests the issue is something specific with github actions or its environment.

**Comment by czlee** [comment]
Oh, yeah, I think that's the `--fetch-depth` thing I tried fixing in #21. Once that's fixed, then the `git diff` error should occur, I think. I'll merge #21 to get past the `fatal: bad object 943ccb5ec645680f842edd98972d0fd9daed4fe7` bit, then we'll tackle this problem?

I think this is also the same error as we were getting in #19:

**Comment by czlee** [comment]
#21 is merged, either merge `main` or rebase onto it and see if that gets us past the `git show` issue 🤓

Though, on this PR, I guess my question is, is the exit code 128 _only_ if it's due to the file not existing? Or does it cover other error conditions (that we wouldn't want to ignore) as well? I couldn't figure this out from the internet/git docs.

**Comment by daankoning** [comment]
Looks like it did!

On exit codes, it seems like it depends on the specific implementation of git being used (as it is more akin to a protocol than a program). On the assumption that github actions uses the standard (Torvald's original) version (which I find to be a somewhat reasonable assumption since the action runs on ubuntu), it seems like it is the result of a subprocess not exiting cleanly (in this case likely trying to acces the non-existant file). Given that, it probably makes sense to go ahead and not merge this commit as 1) you identify this would also catch errors that shouldn't pass silently and 2) #23 should fix the problem as well.

**Comment by czlee** [comment]
Oh, huh, it went for e2286de5c51a2e274df1d7a3b53e2ff7dd20af6b which isn't the commit I intended. So seems like `base_ref` is the _current_ commit of the target branch, not the most recent common ancestor between the target and feature branches.

That's not really what I was going for, but maybe that's okay, since I guess it's what's relevant for merging purposes…

**Comment by daankoning** [comment]
I imagine that in this specific case the issue is caused by merging main (from which this branch is forked in the first place) back into this PR?

**Pull request closed without merging**
