### PR TITLE
Create tgd2022.xml

### PR DESCRIPTION
**Pull request by daankoning**
Supersedes #9. Might be a bit late but it felt nice to clean up all the existing PRs at least 😄.

By submitting this pull request, I agree to license my contributions under the [MIT License](https://github.com/czlee/debatekeeper-formats/blob/main/LICENCE.md).

### CODE REVIEW

**Comment by daankoning** [comment]
Oh, turns out I couldn't just copy paste in the file from #9 😅.  I'll go ahead and patch them up then.

**Comment by daankoning** [comment]
Looks like the current solution still isn't infallible, I've opened up a new issue.

**Comment by daankoning** [comment]
@czlee could you trigger a rerun of the actions on this PR now that everything seems to have been fixed? Thanks a bunch!

**Comment by czlee** [comment]
@daankoning I think we just need to rebase onto master? Then the push should retrigger. (Otherwise it'll just run on the same (old) commit.)

**Comment by daankoning** [comment]
😥 I guess this is being caused by #23? I'll have time to have a longer look later this week

**Comment by czlee** [comment]
Oh, you're right. Just tried it locally, error is that the file doesn't exist (which it doesn't).

**Comment by czlee** [comment]
Okay, there. @daankoning let me know what you think!

I realised it's the same as the existing Thropy format, but I think right now with this repo my unofficial policy is to permit the same formats with different names, since the names will probably make them easier to find, and will allow easier updates if they later diverge.

**Comment by daankoning** [comment]
Good point! You should probably keep them seperate in that case. I have no further comments at this point :)

**Pull request merged**
